### ISSUE TITLE
Discussion: Why not have a list of Open Source Plugins instead of a collection?

### ISSUE THREAD

**Issue by 0xB10C** [renepickhardt/c-lightning-plugin-collection#2]
Re: adding my plugin to the collection

I thought about it a bit and came to the conclusion that a list or table (with links to the original repo, name, description, author, license) might be a good alterative.

Pro: 
- Plugin updates would not require a seperate PR each time
- The author would still have repo ownership
- Custom licenses could be enforced 

Con:
- removed or renamed repos would result in dead links, the plugin would be lost (happens rarely I guess)

Of course plugins could be contained inside the _listrepo_ too. The links inside the Readme would point to the corresponding folders. 

A table/list might look Iike:

| Link | Description | Author | License | (Notes?) |
|------|-----------------------------------|--------|---------|----------| 
|[csvexportpays](https://github.com/0xB10C/c-lightning-plugin-csvexportpays) | Exports past payments as CSV file | [0xb10c](https://github.com/0xb10c) | _placeholder_ | e.g. version v0.7, last updated...|

A row could be added as PR.

What do you think? Did you have something similar in mind?

**Comment by renepickhardt** [comment]
I was thinking of a hybrid solution. Meaning I would copy the plugins that I or a person I trust have checked to make sure they don't disappear in remote repos. Along with that there would be a list of plugins in remote repos that have not been checked or that are under development. In any case keeping the plugins license should not be a problem as long as it is an open source license. Also in any case I would also link to the original repository

**Comment by 0xB10C** [comment]
Sounds good.
